language: python

sudo: false

matrix:
  include: # Specify both TOXENV and python, see https://stackoverflow.com/a/31990486/3109189
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=coveralls-py3

install:
  - pip install --upgrade pip
  - pip install tox-travis

before_script:
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys

script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [[ ! "$TRAVIS_PULL_REQUEST_SLUG" =~ ^algolia\/ ]]; then eval $(./algolia-keys export) && IS_COMMUNITY=TRUE tox; else tox; fi
